# Generated by Django 4.2.7 on 2023-11-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant_product_color_variants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_variants',
            field=models.ManyToManyField(blank=True, to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_variants',
            field=models.ManyToManyField(blank=True, to='products.sizevariant'),
        ),
    ]
